[[plugins]]
repo = 'Shougo/dein.vim'

# 形を整えてくれる
[[plugins]]
repo = 'prettier/vim-prettier'

# 括弧を自動で閉じてくれる
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# 全角の空白を消してくれる
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# tab補完ができる
[[plugins]]
repo = 'ervandew/supertab'

# gitで管理しているファイルの差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# gitのコマンドをvimで実行できる
[[plugins]]
repo = 'tpope/vim-fugitive'

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'

# 複数行をコメントアウトできる
[[plugins]]
repo = 'tpope/vim-commentary'

# チートシートを表示できる
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# リンター
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap ? :'<,'>TComment<CR>
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
